[[redirects]]
  from = "http://commcon.xyz"
  to = "https://2020.commcon.xyz"
  status = 301

[[redirects]]
  from = "https://commcon.xyz"
  to = "https://2020.commcon.xyz"
  status = 200

[[redirects]]
  from = "http://commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"
  status = 200

[[redirects]]
  from = "https://commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"
  status = 200

[[redirects]]
  from = "http://www.commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"
  status = 200

[[redirects]]
  from = "https://www.commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.well-known/matrix/client"
    [headers.values]
    Access-Control-Allow-Origin = "*"
