[[redirects]]
  from = "http://commcon.xyz"
  to = "https://2020.commcon.xyz"

[[redirects]]
  from = "https://commcon.xyz"
  to = "https://2020.commcon.xyz"

[[redirects]]
  from = "http://commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"

[[redirects]]
  from = "https://commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"

[[redirects]]
  from = "http://www.commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"

[[redirects]]
  from = "https://www.commcon.xyz/*"
  to = "https://2020.commcon.xyz/:splat"